config/routes.rb
Rails.application.routes.draw do
  # get 'pages/about'
  get '/about', to: "pages#about"
  # VERB 'path', to: "controller#action", as: :internal_name


  # get 'pages/contact'
  get 'contact', to: "pages#contact", as: :contact

  # get '/', to: "pages#home", as: :home
  root to: "pages#home"


  get '/restaurants', to: "restaurants#index", as: :restaurants

  post '/restaurants', to: "restaurants#create"

  # restaurants/56
  get '/restaurants/:id', to: "restaurants#show", as: :restaurant

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
    # data
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  RESTAURANTS = {
    1 => { name: "Wagas", address: "Donghu Rd, Shanghai", category: "salads" },
    2 => { name: "Yang's Dumplings", address: "West Nanjing, Shanghai", category: "dumpling" }
  }
  def index
    @categories = %w(hunan cantonese hotpot dongbei)
    @food_type = params[:food_type]
    if @food_type.present?
      @restaurants = RESTAURANTS.select {|id, r| r[:category] == @food_type }
    else
      @restaurants = RESTAURANTS
    end

    stupid_method("hello")
  end

  def create
    # r = Restaurant.new(name: params[:name], address: params[:address])
    # r.save
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]
    # @restaurant = Restaurant.find(params[:id])
  end

  def stupid_method(word)
    @name = word
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dianping Ripoff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h3>Simple Header</h3>
    <%= yield %>
    <footer>Mady by Le Wagon</footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>This is My Home Page</h1>
<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>
<%= link_to "Contact", contact_path %>

app/views/restaurants/index.html.erb
<h1>My Fave Restaurants</h1>
<p>My Favorite Restaurants are</p>
<ul>
  <% @restaurants.each do |id, restaurant| %>
    <li><%= restaurant[:name]%> - <%= restaurant[:address] %> (<%= restaurant[:category] %>) <%= link_to "more details", restaurant_path(id) %></li>
  <% end %>
</ul>
<!--  get '/restaurants', to: "restaurants#index", as: :restaurants
 -->
<h5>Your query was: <%= @food_type %></h5>
<form action="restaurants" method="get">
  <input type="text" name="food_type" placeholder="what type of restaurant">
  <input type="text" name="restaurant_name">
  <input type="submit">
</form>
<!-- link_to "What you click on", prefix_path -->
<%= link_to "Home", root_path %>
<%= @name %>

app/views/restaurants/show.html.erb
<h1>More Info About <%= @restaurant[:name] %></h1>